plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '[7.0.17,8)'
}

version = mod_version
group = mod_group_id

base {
    archivesName = "jukeify-forge-${minecraft_version}"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

minecraft {
    mappings channel: 'official', version: minecraft_version

    runs {
        client {
            workingDir = layout.projectDirectory.dir('run')
            mods {
                jukeify {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
    mavenCentral()
}

dependencies {
    implementation minecraft.dependency("net.minecraftforge:forge:${minecraft_version}-${forge_version}")
}

processResources {
    def props = [
        minecraft_version: minecraft_version,
        forge_version: forge_version,
        mod_id: mod_id,
        mod_name: mod_name,
        mod_version: mod_version
    ]
    inputs.properties props
    filesMatching(['META-INF/mods.toml']) { expand props }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release = 25
}
